inherit_from: .rubocop_todo.yml
AllCops:
    NewCops: enable
require:
  - rubocop-rails
Metrics/BlockLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false

Rails/OutputSafety:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false